version: '3'
volumes: 
  #can replace persistent data for mysql (same model for redis)
  dbdata:

services:

  # The Application
  app:
    build:
      context: ./docker
      dockerfile: ./app.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
      - "BEANSTALKD_HOST=queue"
    ports:
      - %port_php%:9000

  # The Web Server
  # web:
  #   build:
  #     context: ./docker
  #     dockerfile: ./web.dockerfile
  #   working_dir: /var/www
  #   volumes:
  #     - .:/var/www
  #     - ./certificates:/etc/nginx/certs
  #   ports:
  #     - 4000:443
  #     - 8000:80

  # The Database
  database:
    image: mysql:5.6
    restart: always
    volumes:
      - ./docker/persistent/mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - "%port_mysql%:3306"

  # # Cache
  # cache:
  #     image: redis:alpine
  #     restart: always
  #     environment:
  #       - "REDIS_PASSWORD=${REDIS_PASSWORD}"
  #     command: redis-server --appendonly yes
  #     volumes:
  #       - ./docker/persistent/redis:/data

  # # Queue handler      
  # queue:
  #     image: schickling/beanstalkd
  #     restart: always
