<?php

namespace Core\Console\Commands\Config;
use Illuminate\Console\Command;
use Symfony\Component\Console\Input\InputOption;
use App;
use Illuminate\Foundation\Providers\ArtisanServiceProvider;
use DB;
use Core\Model\Error;
use File;
use Logger;
use Illuminate\Console\Application;
use Log;

class Export extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'config:export';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate config.json and config.js for frontend';

    /**
     *
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
       $config = config();
       $config = $config->all();

       $path = join_paths(config('front.path'), 'storage','config.json');
    //    Logger::info($path);
       file_put_contents($path, json_encode($config, \JSON_PRETTY_PRINT));
       
       $path = join_paths(config('front.path'), 'src','config.js');
       $config = config('export');
       file_put_contents($path, "/*Autogenerated dont edit*/\nexport default ".json_encode($config, \JSON_PRETTY_PRINT));

    }
}
